FROM stadlerpeter/existdb:6.2.0

# Set the environment for eXist-db. Values 'development' or 'production'
ENV EXIST_ENV=development

# Set the percentage of CPU to be used by the JVM
ENV JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0

# Add local packages to eXist's autodeploy for installing on lanching the database
COPY ./autodeploy/*.xar ${EXIST_HOME}/autodeploy